# docker-compose.yml

version: '3.8'

services:
  hangman-backend:
    build:
      context: ./hangman-backend
    container_name: hangman-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./hangman-backend:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - symfony

  db:
    image: mysql:5.7
    container_name: hangman-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hangman_db
      MYSQL_USER: hangman_user
      MYSQL_PASSWORD: hangman_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony

  nginx:
    build:
      context: ./nginx
    container_name: hangman-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./hangman-backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hangman-backend
    networks:
      - symfony

  hangman-frontend:
    build:
      context: ./hangman-frontend
    container_name: hangman-frontend
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - nginx
    networks:
      - symfony

  hangman-frontend-dev:
    build:
      context: ./hangman-frontend
      dockerfile: Dockerfile.dev
    container_name: hangman-frontend-dev
    restart: unless-stopped
    ports:
      - "4200:4200"
    volumes:
      - ./hangman-frontend:/app
      - /app/node_modules
    networks:
      - symfony
    profiles:
      - development

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8081:80"
    networks:
      - symfony
volumes:
  db_data:

networks:
  symfony:
    driver: bridge
