# hangman-frontend/Dockerfile.dev

FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose Angular's default port
EXPOSE 4200

# Start the Angular development server
CMD ["npm", "start"]
